# Generated by Django 4.2.3 on 2023-07-25 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('show_id', models.IntegerField(default=0)),
                ('show_name', models.CharField(max_length=100)),
                ('show_date', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TitleBelts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weight_class', models.CharField(choices=[('LHW', 'Light Heavyweight'), ('HW', 'Heavyweight'), ('SHW', 'Super Heavyweight'), ('CW', 'Cruiserweight')], max_length=3)),
                ('retired', models.BooleanField(default=False)),
                ('retired_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wrestlers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weight_class', models.CharField(choices=[('LHW', 'Light Heavyweight'), ('HW', 'Heavyweight'), ('SHW', 'Super Heavyweight'), ('CW', 'Cruiserweight')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='WrestlerTitles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_belt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WWEUniverseWebApp.titlebelts')),
                ('wrestler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WWEUniverseWebApp.wrestlers')),
            ],
        ),
        migrations.CreateModel(
            name='WrestlerStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ratio', models.FloatField(default=float("inf"))),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WWEUniverseWebApp.wrestlers')),
            ],
        ),
        migrations.CreateModel(
            name='WrestlerShows',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WWEUniverseWebApp.shows')),
                ('wrestler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WWEUniverseWebApp.wrestlers')),
            ],
        ),
        migrations.AddField(
            model_name='titlebelts',
            name='current_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WWEUniverseWebApp.wrestlers'),
        ),
        migrations.AddField(
            model_name='titlebelts',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WWEUniverseWebApp.shows'),
        ),
        migrations.CreateModel(
            name='ShowTitles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WWEUniverseWebApp.shows')),
                ('title_belt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WWEUniverseWebApp.titlebelts')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('championship_match', models.BooleanField(default=False)),
                ('match_date', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('ppv', models.BooleanField(default=False)),
                ('ppv_name', models.CharField(blank=True, max_length=100)),
                ('ppv_date', models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='WWEUniverseWebApp.wrestlers')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WWEUniverseWebApp.shows')),
                ('title_belt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WWEUniverseWebApp.titlebelts')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='WWEUniverseWebApp.wrestlers')),
                ('wrestler_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrestler_one', to='WWEUniverseWebApp.wrestlers')),
                ('wrestler_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrestler_two', to='WWEUniverseWebApp.wrestlers')),
            ],
        ),
    ]
